# This is a config for E2B sandbox template.
# You can use template ID (fn2qy8ka6kmbt9avtyo4) or template name (lovable-app) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("lovable-app") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-app") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-app')

team_id = "e337f2b5-d188-4e3e-8567-50d0edadc80f"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-app"
template_id = "fn2qy8ka6kmbt9avtyo4"
